spring:
  application:
    name: api_dvdrental
  datasource:
    url: jdbc:postgresql://localhost:5432/dvdrental
    username: postgres
    password: prajjwal7
    hikari:
      connectionTimeout: 20000
      maximumPoolSize: 5
    jpa:
      hibernate:
        ddl-auto: create
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect
management:
  endpoints:
    web:
      exposure:
        include: "*"

server:
  port: 8081